name: build and deploy - 001 - homologacao

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: version node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: Dependency vulnerability scan
        run: npm audit --audit-level=critical
        
      - name: run lining
        run: npm run lint

      - name: run typecheck
        run: npm run typecheck

      - name: run build
        run: npm run build
        env:
         MONGODB_URI: ${{ secrets.MONGODB_URI }}
         SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

